version: "3.7"
services:
  mysql:
    container_name: mysql-container
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=onpurple
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    env_file:
      - .env

  redis:
    container_name: redis-container
    image: redis
    ports:
      - "6379:6379"